language: cpp

distro: archlinux
distro: fedora
distro: gentoo

jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install libucl-dev libgtk-3-dev meson
      - wget https://github.com/wmww/gtk-layer-shell/archive/v0.1.0.tar.gz -O /tmp/glsh.tar.gz
      - cd /tmp
      - tar -xvf glsh.tar.gz
      - cd gtk-layer-shell-0.1.0
      - meson build
      - ninja -C build
      - ninja -C build install
    script:
      - meson build
      - ninja -C build
