language: cpp

arch: amd64
os: linux
dist: focal

env:
  global:
    -secure: "LjQv9i1ATu2LIGm6X0Fomv1PWGK7e11Our+39MYhRxgp+CoWlrEQBvRwWwX6znCUbwFQNmQD2JLPsEEbSWXPBVXf6QG/de2uDUvAcFPsBh91VDHcLyWhW8ptJPLXPY2EnOsmFe3QbjctakD25loKSDQlS3y46Xu/tktgCZ8uogNymt+XaFRh8F7zltds7GYh5wHXIUEZBl2AIWuoO/4jB4zWB3t6MS/cXVmOuBTYKabdT7QgMivW0gYIZUe8MSpTWKSZi6dToYThHjyxbn1G9twFOvE3GLK8KetdU4/5cBTP+EGxHOMLjQORdzq2kV6KR4EY+hzjc+Qvx/r0nHqHwvJoJ7i5P7Ad9OgkdP74O6x6wLRv+DzJiSuBXuaLYkfuogtFT2sxbDkzoCkBjD62q55U7lzx92kJrxAuAK6t1JNkH6GI3gia+47x6Zd5qX5cWwQg20OwZbrsdNrplfyv3QRp3TTa1E7rxiiiMWfAnlwROwCTqlyjPGCq1L1Pa6q9ucL0s301LL40RQAq0GgFGIcw7/cn25bLIBNG5ZDPJfcdb1kKwS12gkygTf9xmkm5sHHijnqFoW8NJk+a/1vu6K+ATvGNQlPSw+kt09MFJbyvtZnmvmU8ORFVGsoo2hdwWWx//rJiRD2W7wOy3vujG4M1iv+GNM6+2FH2sDA66y4="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install libgtk-3-dev meson libgtk-layer-shell-dev
      - wget https://github.com/vstakhov/libucl/archive/0.8.1.tar.gz -O /tmp/libucl.tgz
      - pushd /tmp
      - tar -xvf libucl.tgz
      - cd libucl-0.8.1
      - ./autogen.sh
      - ./configure
      - make
      - sudo make install
      - popd
    script:
      - meson build
      - ninja -C build

addons:
  coverity_scan:
    project:
      name: "LBCrion/sfwbar"
      description: "SFWBar"
    notification_email: harley@hosers.org
    build_command_prepend: "meson build"
    build_command: "ninja -C build"
    branch_pattern: main
