language: cpp

distro: archlinux
distro: fedora
distro: gentoo

jobs:
  include:
    compiler: gcc
    before_install:
      - sudo pkg install -y gtk-layer-shell libucl libgtk-3-dev
    script:
      - meson build
      - ninja -C build
