language: cpp

arch: amd64
os: linux
dist: focal

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "elzH11r6PXDxBMvSCVuVh2sK6g/SJoy7otMs3wFRBKuJeoWraHKSakm2pxZ/Aggs9rpxFUwy2RBM7hljaSOYbvJrPyQKXFyIFg4OY+YqZAiggvjhrMhreMT9X7SAoRAIyfDvRZUxzngdYQxXGZyqwstZ0DzN7zaI0tRDK7WsdHoG7HjIbBX4+KfWaI8Pq/VIsRevPJF0LYWGxc9u9Tsq0WA1KfCMWfgmGhahWNt8s/6I4veKTyqavEWV8zkHJX8sT3OuwphVrqXRXuZ7tsWYnqQmPNjr3NN9E/YHm/mvBphOKKlh4ExEd97NL2cX5ZqetFdJUMWI3ZybkdsL26ieYsI+8EJVqcfzK9UvWEKNz7RrJL7N3r993LIqfGfzuQzmkdJZiflzn7k4p3/9hnp+7xePTQwfDKPkg2QgbP5k+IJkM0b8JhtCI1yxMBgOTSzyW1jrMDh+YX43jSgg9g2L4w5uRd7kUvTinlYkld7Xb2Yv9EI9gpiZ0QT1WSqPVIPorT4rPOfrq9/wd9PrhmBpmgKlzvaxH/34cRK5dUOBkbfr9tm5MDH4xSESdtV8uSCgf5yysbq5E/6CHQdQHg4EssmnMsBUPM6jA7kPQGNWFbMCzGr2HLyTMvt+tc1JtfzG6afstqWV0+2CWNA4o+Vd4AL20m2k0/Qxn4oblFCCUGk="

before_install:
  - true | openssl s_client -connect scan.coverity.com:443 | openssl x509 | sudo tee -a /etc/ssl/certs/ca-certificates.crt

jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get -y install libgtk-3-dev meson libgtk-layer-shell-dev
      - wget https://github.com/vstakhov/libucl/archive/0.8.1.tar.gz -O /tmp/libucl.tgz
      - pushd /tmp
      - tar -xvf libucl.tgz
      - cd libucl-0.8.1
      - ./autogen.sh
      - ./configure
      - make
      - sudo make install
      - popd
    script:
      - meson build
      - ninja -C build

addons:
  coverity_scan:
    project:
      name: "LBCrion/sfwbar"
      description: SFWBar
    notification_email: harley@hosers.org
    build_command_prepend: "meson build"
    build_command: "ninja -C build"
    branch_pattern: main
