language: cpp

distro: archlinux
distro: fedora
distro: gentoo

jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install libgtk-layer-shell-dev libucl-dev libgtk-3-dev
    script:
      - meson build
      - ninja -C build
