language: cpp

arch: amd64
os: linux
dist: focal

before_install:
  - true | openssl s_client -connect scan.coverity.com:443 | openssl x509 | sudo tee -a /etc/ssl/certs/ca-certificates.crt

jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install libgtk-3-dev meson libgtk-layer-shell-dev libjson-c-dev
    script:
      - meson build
      - ninja -C build

addons:
  coverity_scan:
    project:
      name: "LBCrion/sfwbar"
      description: SFWBar
    notification_email: harley@hosers.org
    build_command_prepend: "meson build"
    build_command: "ninja -C build"
    branch_pattern: main
