language: cpp

arch: amd64
os: linux
dist: focal

jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install libucl-dev libgtk-3-dev meson libgtk-layer-shell-dev
    script:
      - meson build
      - ninja -C build
