language: cpp

arch: amd64
os: linux
dist: focal

env:
  global:
    - secure: "SuRNSMZvbACENBy/TTTlqhOfRE/oYc6Kqs1hEyR6I9sgE4dDP7BwDP6Wa2TFgpHlqmbX8ICfjv7H/PHT3+1CqhZNN3pYvyJcrx8jQTger19um0kTq/bGhpCQEacW52xaXhUzrX+ZkmovETz3rI24xwlwS8tbUdJtoItDKQJ/BxIctUHOr/7mJTyYGMMYx9lNgMvhpl9NBkSfCQmrrXB/q9hh/bwR1UD/OCj/KV4wA1IpSKt/tRVM24f0iJDZoODOSSGQdbgW8scLkmHaCg3HoO5aOw83KM/L+tv6MTcrWtHv9JnY9w74H3FxTKh4fbaRmJc2PdkJuFUtWkwIxg2x06BTt2Vp3Ce2RnyX5VLf1RypGN0DgXfu1hHfB/SYWm1tUmi0YnjLZvw1rNQQDyAai7m6u8r5QkLGZ0yk0WxgGPx0Lop5xI7iZlIqrOawvDx8xQBnpKP6zV7+QJO7SDkr1YbsUqPHLVNtqC+BUpEmdApBtedVh/EWUe7kNCpqLMG4ZI+cfJZ5Z52jBdUT91ueQ1Oki5ljFNMy4Ukt6oB9fRguXAlpRPcoXPLHRQ7M/UEWMyeOvaaRoQB1+IOk05P0xwhGC84IjbABe1hbZF8gEdXvr0oeYUMce8wZFdRQuzBvSwuJok1LMMeUpGTWgi8vkhxCtEr0nahRYU/hZw/MxSc="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


jobs:
  include:
    compiler: gcc
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install libgtk-3-dev meson libgtk-layer-shell-dev
      - wget https://github.com/vstakhov/libucl/archive/0.8.1.tar.gz -O /tmp/libucl.tgz
      - pushd /tmp
      - tar -xvf libucl.tgz
      - cd libucl-0.8.1
      - ./autogen.sh
      - ./configure
      - make
      - sudo make install
      - popd
    script:
      - meson build
      - ninja -C build

addons:
  coverity_scan:
    project:
      name: LBCrion/sfwbar
      description: SFWBar
    notification_email: harley@hosers.org
    build_command_prepend: meson build
    build_command: ninja -C build
    branch_pattern: main
